### ISSUE TITLE
✨ [FEAT]: CMS/FE - Add Collections Listing Page

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1001]
### Summary

Do it

### Tasks

- [ ] use "name" and "slug" for all collections
- [ ] export cms config
- [ ] update API shapes with field names
- [ ] refactor slug and one-offs

### URL

https://www.dgrebb.com/
