### ISSUE TITLE
🧹 [CHORE]: FE/CMS - refactor Projects Video component

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1005]
### Summary

Remove the fields above details for videos now that upload works.

### Tasks

- [ ] remove video file and caption text fields
- [ ] add caption text field to artifact details
- [ ] adjust API shape
- [ ] adjust projects route and page
