### ISSUE TITLE
[REFA]: FE - Initialize a new Sveltekit project and copy files in for a fresh start

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1014]
### Summary

Recreate the app with a clean slate using jsdoc as the typing mechanism and build tooling.

### Tasks

- [x] do pnpm issue first
- [x] move files to tmp 
- [x] install new project in front
- [x] copy conifg and whatnot in
- [x] test
- [x] test more
- [ ] test with backstop

### URL

https://www.dgrebb.com/
