### ISSUE TITLE
✨ [FEAT]: FE - CV - Animate Date on Timeline

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1015]
### Summary

The date of each position should slide out either on hover or on intersection of viewport.

![Image](https://github.com/dgrebb/dgrebb.com/assets/445891/a7b16696-3c4b-4cff-98a0-0dbaaf5ba5a5)

### Tasks

- [ ] make the transition
- [ ] try it with CSS only
- [ ] try it with `intersectionObserver`

### URL

https://www.dgrebb.com/
