### ISSUE TITLE
✨ [FEAT]: FE - Aside Navigation Accordions

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1018]
### Summary

Make each aside heading its own accordion.

Expanded / Collapsed state of Aside section, if shared across pages (like CV sections, or between Posts and Categories).

### Tasks

- [ ] create the necessary markup to achieve this without CSS or JS (`details`/`summary`
- [ ] test what this looks like in mini nav
- [ ] apply styles
- [ ] apply any needed JS
- [ ] add UI Helpers for user data

### URL

https://www.dgrebb.com/
