### ISSUE TITLE
✨ [FEAT]: FE - Create Skill Component

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1019]
### Summary

Create a drop-in place component for skills. It should provide for:

- proficiency scale
- logo
- name
- years used (calculate this from first-last project dates)

### Tasks

- [ ] create the component
- [ ] write the math functions
- [ ] create the scale component
- [ ] style it
- [ ] tests

### URL

https://www.dgrebb.com/
