### ISSUE TITLE
✨ [FEAT]: FE - Set up API and CV Page with SEO

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1024]
### Summary

All the bells and whistles, including social, meta image, description, keywords, etc.

### Tasks

- [ ] establish the API pattern
- [ ] pull data into CV page
- [ ] wire up `MetaTags` and `Meta`
- [ ] test, test, test

### URL

https://www.dgrebb.com/
