### ISSUE TITLE
🧹 [CHORE]: FE - Extract Reusable Svelte Components

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1026]
### Summary

General component reuse and refactoring.

### Tasks

- [ ] extract positions, skills, orgs, sidebar collections into components
- [ ] extract reuseable cv atoms into composable pieces of collection components
- [ ] pull any JS manipulation into the server
