### ISSUE TITLE
✨ [REFA]: Rename "Positions" "Experiences"

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1027]
### Summary

The "Positions" word doesn't really serve the purpose of this collection. Education, Teaching, Freelance, Volunteering, and ongoing opensource responsibilities should be included.

### Tasks

- [x] rename the API
- [x] Adjust all relations fields
- [x] change API patterns in FE
- [x] rename components and routes
- [x] check SEO

### URL

https://www.dgrebb.com/
