### ISSUE TITLE
✨ [FEAT]: FE - CV - Adapt the Timeline to All Collections

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1036]
### Summary

Using the timeline pattern, create a component that accepts items, dates, and their respective display elements in slots and views.

Animate transitions between each collection, sliding the timeline items in or out, and expanding the timeline much like the categories page grows and collapses.

The timeline itself will need to be attached to the container, as opposed to the underlying timeline items. The timeline points can remain where they are, but should be renamed and reusable across all collections.

Collections like Skills and Organizations might make less sense using this layout, so adjust as needed, and plan new work as it comes up.

### Tasks

- [ ] design each timeline view
  - [ ] design each collection's timeline item layout
- [ ] design the views for skills, classifications, industries, and organizations (though orgs may be timeline-applicable)

### URL

https://www.dgrebb.com/cv/projects
