### ISSUE TITLE
✨ [FEAT]: CMS - Refactor Rich Text fields with "Block" Field Type

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1037]
### Summary

In preparation for Strapi 5, update all rich text to block fields. Copy content as needed.

### Tasks

- [ ] identify fields by searching schema
- [ ] add new fields and name them "bodyText" or something that makes it easy to migrate
- [ ] copy content from old fields
- [ ] export configuration updates

### URL

https://www.dgrebb.com/
