### ISSUE TITLE
✨ [FEAT]: FE - Refactor Mini-Nav with `details`/`summary`

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1039]
### Summary

Refactor the mini-nav with `summary` and `details` elements, eliminating the need for CSS input checkbox selectors.

Make the component content-independent, and reusable for different sections of the site including the CV section experiences projects, etc. 

Also use a small amount of JS to handle overlay behind mininav, but assume `:has()` will be used in near future and JS can be removed.

For now, use JS to apply a class to the `body` tag to achieve overlay background.

### Tasks

- [ ] refactor mini-nav as independent component with groups of links as the props
- [ ] restyle the mini-nav with `summary`/`details`
- [ ] styles for overlay background
- [ ] small JS util to apply `body` classname when mini-nav is active

### URL

https://www.dgrebb.com/
