### ISSUE TITLE
🧹 [CHORE]: CMS - Finalize CVMVP Content and Publish Production

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1044]
### Summary

Tidy up CV summary content, organizations, and skills. Remove the `**/cv/**` wildcard from sitemap ignore.

### Tasks

- [x] add all skills
- [x] add all organizations and related skills
- [ ] add all experiences, dates, summary content, and orgs/skills relations
- [ ] remove sitemap ignore wildcard, add sub sections to ignore
