### ISSUE TITLE
✨ [FEAT]: CMS/FE - Add Social Icon Links to CV Content Type

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1050]
### Summary

Use a separate social links source via custom field in the CV landing page singleton. 

### Tasks

- [ ] add CMS fields
- [ ] remove social link changes to Home and layout APIs
- [ ] revert Home section back to original pattern
- [ ] add new social link data to CV API
- [ ] style if needed

### URL

https://www.dgrebb.com/cv
