### ISSUE TITLE
✨ [FEAT]: FE - Animate and Indicate Experience End Dates

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1059]
### Summary

On hover at larger breakpoints, animate an arrow coming out of the experience title's bottom border, and slide out the end date of that experience.

### Tasks

- [ ] use a conditional to determine if dates and if end date
- [ ] add enddate markup
- [ ] style enddate
- [ ] add arrow
- [ ] style arrow and enddate
- [ ] animate arrow onhover
- [ ] determine layout for mobile (if any)

### URL

https://www.dgrebb.com/
