### ISSUE TITLE
🧹 [CHORE]: FE - Remove Sentry

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1062]
### Summary

Just don't use it. 800KiB is not worth the benefit of seeing real-world errors. Look into a leaner solution.

### Tasks

- [x] remove Sentry from vite configs
- [x] remove Sentry imports from all front end files
- [x] take before and after snapshots of the bundle size
