### ISSUE TITLE
🐞 [BUG]: FE - Hide Timeline `endDate` animations and dot when dates are hidden

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1069]
### What happened?

![Image](https://github.com/dgrebb/dgrebb.com/assets/445891/2a141bd3-0611-42fe-9600-976c59e7d4be)

### Tasks

- [ ] try animating the lines all the way when dates are hidden
- [ ] remove the dot
- [ ] test
- [ ] add backstop tests for hidden/shown dates

### Relevant log output

https://local.dgrebb.com/cv/
