### ISSUE TITLE
✨ [FEAT]: FE - Refactor MetaTags without svelte-meta-tags

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1074]
### Summary

The conditional logic in `svelte-meta-tags` is blowing up to 100KB after compilation.

Remove it.

### Tasks

- [x] copy logic into local component
- [x] delete `svelte-meta-tags` from `package.json`
- [ ] remove excessive conditionals and isolate what you use
- [ ] reduce logic as much as possible by providing fallbacks from meta properties

### URL

https://www.dgrebb.com/
