### ISSUE TITLE
✨ [FEAT]: FE - Internal Link Previews

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1112]
### Summary

Use, shallow routing to create a post, skill, job, organization, etc. preview-on hover component.

Call it `HoverCard.svelte`.

### Tasks

- [ ] research and explore shallow routing
- [ ] create `HoverCard.svelte`
- [ ] implement across posts, experiences, categories, etc.

### URL

https://www.dgrebb.com/
