### ISSUE TITLE
🧹 [CHORE]: FE - refactor CSS processing with `sass` alone...

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1117]
### Summary

ensure future compatibility and removal when new features are added

### Tasks

- [ ] move css into svelte components where possible
- [ ] use `lang="scss"` in `<style>`
- [ ] ensure media queries don't break
- [ ] check errors for anything postcss was doing

**Comment by dgrebb** [comment]
This isn't possible. PostCSS is needed to make nested `&_child-BEM` work. Oh well ¯\_(ツ)_/¯
