### ISSUE TITLE
✨ [FEAT]: CI - Add Security Headers to CloudFront

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1139]
### Summary

https://dev.to/aws-builders/apply-cloudfront-security-headers-policy-with-terraform-fd3

### Tasks

- [ ] test various headers on STG
- [ ] adjust TF modules as needed
- [ ] apply to STG and rerun SiteOne Crawler
- [ ] push to PRD

### URL

https://www.dgrebb.com/
