### ISSUE TITLE
✨ [FEAT]: FE - Refactor configuration and upgrade to eslint@9.0.0

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1268]
## ESLint 9.0.0

- [migration guide](https://eslint.org/docs/latest/use/migrate-to-9.0.0)
- migrate all FE code to function in eslint 9 — sveltekit included

### Tasks

- [ ] update all frontend deps
- [ ] refactor eslint config files in flatconfig
- [ ] address any new formatting/linting errors
- [ ] test

### URL

https://www.dgrebb.com/
