### ISSUE TITLE
🐞 [BUG]: CI - reports.dgrebb.com showing up in google index

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1278]
### What happened?

Fix it and remove previously indexed pages from search.

### Tasks

- [ ] add robots.txt
- [ ] research other ways to block a domain
- [ ] test
- [ ] remove search indicies
- [ ] check robots.txt and indexability after running a backstop test
