### ISSUE TITLE
✨ [FEAT]: CI - Instance Suspenion After Inactivity

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1292]
### Summary

Refactor TF modules to support automatically shutting down Strapi after a period of inactivity. 

Add a caching layer. Maybe.

### Tasks

- [ ] identify best solution for stops
- [ ] identify best solution for starts
- [ ] apply the same to RDS, ALB
  - [ ] create additional issues if necessary

### URL

https://www.dgrebb.com/
