### ISSUE TITLE
🗺️ [PLAN]: dgreb.com 5.0 Release

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#1330]
### Summary

Strapi 5, Svelte 5, and removing AWS and IaC.

### Tasks

- [ ] start from scratch
- [ ] plan infra
  - [ ] how much cheaper is it to run Strapi with sqlite?
  - [ ] local CMS only?
  - [ ] deploy to S3
  - [ ] how to gate production deployments and move them to stg via github
- [ ] refactored BE Strapi 5 (cms api)
- [ ] refactored FE Svelte 5
- [ ] something else entirely?

### URL

https://www.dgrebb.com/
