### ISSUE TITLE
frontend - add tabindex to post page so toc is first in order on desktop

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#821]
### Priority

⦿ ⦿ ⦿ ⦿ ⦿

### Summary

currently the user must have all the way through an article before getting to the sidebar make the aside the first focus, Abel element so that the user can navigate through the table of contents and related information first or perhaps make the related information, after the article and change the tab index of that contained group different 

### Tasks

- [ ] explore grouping aside lists separately in tabindex
- [ ] add tabindex to .post-article
- [ ] add tabindex to aside
- [ ] other opportunities for improvement
- [ ] test

**Comment by dgrebb** [comment]
already achieved by post heading navigation via focus on anchor links
