### ISSUE TITLE
✨ [FEAT]: CMS - Animated Image Content Component

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#822]
### Summary

for posts with gif demos, use inline html combined with svelte markdown or a new content type to load a static image and then animated gif on play/pause

https://css-tricks.com/pause-gif-details-summary/

### GitHub's GIF Player

![Image](https://github.com/dgrebb/dgrebb.com/assets/445891/75742064-df44-436b-86af-ac96b1033f91)

### Tasks

- [x] add content type
  - [x] title
  - [x] image
    - [x] alt
  - [x] still image
  - [x] figcaption
- [x] add html wrapper for player
- [x] add fig and figcaption
- [x] add new content type to Post.svelte
- [x] update local `PUBLIC_POST_PARAMS` secret in `pass`
- [x] test
- [x] confirm CMS field names and commit schema changes
- [x] build image for STG
  - [x] push image to ECR
  - [x] apply terraform
- [x] update GitHub `PUBLIC_POST_PARAMS` secret
- [x] test a STG deployment
- [x] build image for PROD
- [ ] address #847
