### ISSUE TITLE
✨ [FEAT] - CMS - add Projects collection type

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#828]
### Priority

⦿ ⦿ ⦿

### Summary

Add the project content type and fields to CMS configuration.

### Tasks

- [ ] add Projects content type
- [ ] add "job relationship
- [ ] add custom fields
  - [ ] title
  - [ ] organization (school, organization)
  - [ ] subtitle (job title, position, role, etc)
  - [ ] category (volunteering, contribution, professional, photography, application, website, utility, plugin, extension, template, boilerplate, etc)
  - [ ] dates (from/to)
  - [ ] images
  - [ ] urls
  - [ ] credits/collaborators
- [ ] wire up SEO field
