### ISSUE TITLE
✨ [FEAT] - FE add CV Singleton route

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#829]
### Priority

⦿ ⦿ ⦿

### Summary

Add the landing page singleton to CMS Pages

### Tasks

- [ ] create singleton
- [ ] add custom fields
  - [ ] title
  - [ ] summary
- [ ] wire up SEO
  - [ ] create share banner
  - [ ] add share banner
