### ISSUE TITLE
✨ [FEAT] - FE - create CV route and API query

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#832]
### Summary

Add the landing page component and server route's parameters for content API.

### Tasks

- [ ] add `+page.svelte`
- [ ] add `+page.server.js`
- [ ] add `PUBLIC_API_PATH` for jobs
- [ ] add `PUBLIC_API_PATH` for projects
- [ ] determine needed query params, create local and GitHub secrets
- [ ] test
- [ ] leave unstyled for (#833)

### URL

https://www.dgrebb.com/
