### ISSUE TITLE
✨ [FEAT] - CMS - add "Jobs" collection type

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#836]
### Summary

This content type should be used for professional positions, and can be used to associate projects back to jobs.

### Tasks

- [ ] add Jobs content type
- [ ] add "projects" relationship
- [ ] add associated jobs (for example, think browstone, or happy cog for the USHMM project)
- [ ] add custom fields
  - [ ] title (position)
  - [ ] organization (school, organization)
  - [ ] category (volunteering, contribution, professional, photography, application, website, utility, plugin, extension, template, boilerplate, etc)
  - [ ] dates (from/to)
  - [ ] images
  - [ ] urls
- [ ] wire up SEO field

### URL

https://www.dgrebb.com/
