### ISSUE TITLE
✨ [FEAT] - FE - style AnimatedImage component

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#847]
### Summary

Now that the Animated Image content component and API changes are ready in Strapi, style the placeholder AnimatedImage Svelte component.

### Tasks

- [ ] refactor GIF player
- [ ] stylize inline images with `grape` and `sand` theme colors
- [ ] find suitable iconify svgs for play/pause states
- [ ] ensure gif controls are focusable
- [ ] style `focus-visible` state
- [ ] style figure caption
- [ ] see about transitioning the still image so there isn't a FOUC

### URL

https://www.dgrebb.com/
