### ISSUE TITLE
🧹 [CHORE] - FE - Remove Sentry Replay

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#872]
### Summary

The replay bundle is ~60KiB. This is a dealbreaker. 

### Tasks

- [ ] see if there's a way to only remove replay, and if not, completely remove sentry
- [ ] update `init`
- [ ] update hooks
- [ ] remove from static pages
- [ ] remove from configuration
