### ISSUE TITLE
✨ [FEAT]: Add sitespeed.io

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#878]
### Summary

Lighthouse should be replaced with sitespeed.io.

### Tasks

- [ ] create local utils
- [ ] create sitespeed.io workflow
- [ ] archive lightspeed workflow
- [ ] enhance workflow summaries

### URL

https://www.dgrebb.com/
