### ISSUE TITLE
✨ [FEAT]: FE - Add Click Capture to Code Component Copy Button

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#885]
### Summary

Let's see what code copying sets the highest click counts.

### Tasks

- [ ] configure click group in Plausible
- [ ] add event
- [ ] tie in component index, page title, path, etc
- [ ] send event to p.dgrebb.com
- [ ] test

### URL

https://www.dgrebb.com/
