### ISSUE TITLE
🧹 [CHORE]: FE - take a sampling of application size and loadtimes

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#922]
### Summary

Take a before/after sampling of report metrics, browser perf sessions, bundle sizes, etc.

https://www.projectwallace.com/

### Tasks

- [x] lighthouse reports - save to archive director (run them from Chrome, not CLI or GH)
  - [x] take a snapshot of the bundle analyzer eg. https://googlechrome.github.io/lighthouse/treemap/?gzip=1#
- [x] chrome performance samplings while: 
  - [x] navigating through the site front-> back
  - [x] static pages: home, privacy, posts, post, category
- [x] entire build directory size
- [x] file sizes
  - [x] index.html
  - [x] app.js
  - [x] any other bundles that are loaded after first page
- [x] entire project directory size
- [x] node_modules size
- [x] build time for local build with STG
- [x] build time in GH Actions

**Comment by dgrebb** [comment]
# PROD | Wallace Run 23.11.01 ~18:00 ET

```shell
> curl https://www.dgrebb.com | wallace

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  160k  100  160k    0     0  1274k      0 --:--:-- --:--:-- --:--:-- 1306k
───────────────────────────────────────────────────────────
Lines of Code │ Filesize │ Rules │ Selectors │ Declarations
4,438         │ 164.5KB  │ 1,000 │ 2,022     │ 2,304
───────────────────────────────────────────────────────────

Comments                      0B    (0 items)
Embedded Content              0B    (0 items)

Rulesets             Most common      Average      Maximum
Selectors / rule               1         2.03           21
Declarations / rule            1         2.29           75
Empty rules                                              0

Selectors            Most common      Average      Maximum
Complexity                     3         5.63           21
Specificity                0/2/1  0.1/2.7/1.0        1/8/3

                           Total       Unique        Ratio
All Selectors              2,022        1,500        74.2%
ID Selectors                 118          104        88.1%
Accessibility                  1            1       100.0%
Vendor prefixed               63           56        88.9%

AtRules                    Total       Unique     Unique %
@media                        99           12        12.1%
@supports                      2            2       100.0%
@font-face                     6            6       100.0%
@import                        0            0         0.0%
@keyframes                     1            1       100.0%
@container                     0            0         0.0%
@property                      0            0         0.0%

Declarations               Total       Unique     Unique %
All Declarations           2,304          884        38.4%
!important                    53

Properties                 Total       Unique     Unique %
All Properties             2,304          298        12.9%
Custom Properties            247          149        60.3%
Vendor Prefixed               56           21        37.5%
Browserhacks                   0            0         0.0%

Values                     Total       Unique     Unique %
Colors                       359          114        31.8%
Gradients                     70           14        20.0%
Font-sizes                    51           20        39.2%
Font-families                 40           18        45.0%
Line-heights                  35           14        40.0%
Text-shadows                   4            1        25.0%
Box-shadows                   55            8        14.5%
Z-indexes                     25           13        52.0%
Vendor Prefixed                1            1       100.0%
Browserhacks                   0            0         0.0%
Units                        704            8         1.1%
```

**Comment by dgrebb** [comment]
# STG | Wallace Run 23.11.01 ~18:00 ET

- Colors refactored and theme application moved to component-level declaration
- Tailwind `@apply` and `@screen` utils removed
- Tailwind remains part of configuration, dependencies
- Tailwind imports remain in `globals.css`

```shell
> curl https://stg.dgrebb.com | wallace

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90294  100 90294    0     0   168k      0 --:--:-- --:--:-- --:--:--  169k
───────────────────────────────────────────────────────────
Lines of Code │ Filesize │ Rules │ Selectors │ Declarations
2,620         │ 90.3KB   │ 472   │ 859       │ 1,657
───────────────────────────────────────────────────────────

Comments                      0B    (0 items)
Embedded Content              0B    (0 items)

Rulesets             Most common      Average      Maximum
Selectors / rule               1         1.83           21
Declarations / rule            1         3.47           77
Empty rules                                              0

Selectors            Most common      Average      Maximum
Complexity                     3         4.13           15
Specificity                0/1/1  0.0/1.9/0.9        1/7/2

                           Total       Unique        Ratio
All Selectors                859          575        66.9%
ID Selectors                  40           40       100.0%
Accessibility                  1            1       100.0%
Vendor prefixed               12           11        91.7%

AtRules                    Total       Unique     Unique %
@media                        91           13        14.3%
@supports                      2            2       100.0%
@font-face                     6            6       100.0%
@import                        0            0         0.0%
@keyframes                     1            1       100.0%
@container                     0            0         0.0%
@property                      0            0         0.0%

Declarations               Total       Unique     Unique %
All Declarations           1,657          812        49.0%
!important                    10

Properties                 Total       Unique     Unique %
All Properties             1,657          323        19.5%
Custom Properties            345          179        51.9%
Vendor Prefixed               37           18        48.6%
Browserhacks                   0            0         0.0%

Values                     Total       Unique     Unique %
Colors                       171           85        49.7%
Gradients                     48           15        31.3%
Font-sizes                    51           20        39.2%
Font-families                 40           14        35.0%
Line-heights                  35           15        42.9%
Text-shadows                   0            0         0.0%
Box-shadows                   16            6        37.5%
Z-indexes                     21           13        61.9%
Vendor Prefixed                1            1       100.0%
Browserhacks                   0            0         0.0%
Units                        594            8         1.3%
```

**Comment by dgrebb** [comment]
# SvelteKit Buildtime - 23.11.01 21:44 

## `dg f b s`

```shell
> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
✓ built in 18.51s
```

**Comment by dgrebb** [comment]
# SvelteKit Buildtime - 23.11.01 22:19

## `dg f b s`

### After removing Tailwind from config and build

```shell
> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
✓ built in 16.98s
```

**Comment by dgrebb** [comment]
# PROD | Wallace Run 23.11.01 22:49

```shell
Testing CSS on PROD
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  160k  100  160k    0     0   471k      0 --:--:-- --:--:-- --:--:--  473k
───────────────────────────────────────────────────────────
Lines of Code │ Filesize │ Rules │ Selectors │ Declarations
4,438         │ 164.5KB  │ 1,000 │ 2,022     │ 2,304
───────────────────────────────────────────────────────────

Comments                      0B    (0 items)
Embedded Content              0B    (0 items)

Rulesets             Most common      Average      Maximum
Selectors / rule               1         2.03           21
Declarations / rule            1         2.29           75
Empty rules                                              0

Selectors            Most common      Average      Maximum
Complexity                     3         5.63           21
Specificity                0/2/1  0.1/2.7/1.0        1/8/3

                           Total       Unique        Ratio
All Selectors              2,022        1,500        74.2%
ID Selectors                 118          104        88.1%
Accessibility                  1            1       100.0%
Vendor prefixed               63           56        88.9%

AtRules                    Total       Unique     Unique %
@media                        99           12        12.1%
@supports                      2            2       100.0%
@font-face                     6            6       100.0%
@import                        0            0         0.0%
@keyframes                     1            1       100.0%
@container                     0            0         0.0%
@property                      0            0         0.0%

Declarations               Total       Unique     Unique %
All Declarations           2,304          884        38.4%
!important                    53

Properties                 Total       Unique     Unique %
All Properties             2,304          298        12.9%
Custom Properties            247          149        60.3%
Vendor Prefixed               56           21        37.5%
Browserhacks                   0            0         0.0%

Values                     Total       Unique     Unique %
Colors                       359          114        31.8%
Gradients                     70           14        20.0%
Font-sizes                    51           20        39.2%
Font-families                 40           18        45.0%
Line-heights                  35           14        40.0%
Text-shadows                   4            1        25.0%
Box-shadows                   55            8        14.5%
Z-indexes                     25           13        52.0%
Vendor Prefixed                1            1       100.0%
Browserhacks                   0            0         0.0%
Units                        704            8         1.1%
```

**Comment by dgrebb** [comment]
# STG | Wallace Run 23.11.01 22:50

## After removing Tailwind from config and build

```shell
Testing CSS on STG
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 88776  100 88776    0     0   390k      0 --:--:-- --:--:-- --:--:--  395k
───────────────────────────────────────────────────────────
Lines of Code │ Filesize │ Rules │ Selectors │ Declarations
2,524         │ 88.8KB   │ 479   │ 848       │ 1,569
───────────────────────────────────────────────────────────

Comments                    153B    (2 items)
Embedded Content              0B    (0 items)

Rulesets             Most common      Average      Maximum
Selectors / rule               1         1.78           21
Declarations / rule            1         3.24           42
Empty rules                                              0

Selectors            Most common      Average      Maximum
Complexity                     3         4.26           23
Specificity                0/1/1  0.0/1.9/0.9        1/7/2

                           Total       Unique        Ratio
All Selectors                848          562        66.3%
ID Selectors                  40           40       100.0%
Accessibility                  1            1       100.0%
Vendor prefixed               14           12        85.7%

AtRules                    Total       Unique     Unique %
@media                        94           14        14.9%
@supports                      2            2       100.0%
@font-face                     6            6       100.0%
@import                        0            0         0.0%
@keyframes                     1            1       100.0%
@container                     0            0         0.0%
@property                      0            0         0.0%

Declarations               Total       Unique     Unique %
All Declarations           1,569          761        48.5%
!important                     9

Properties                 Total       Unique     Unique %
All Properties             1,569          274        17.5%
Custom Properties            251          132        52.6%
Vendor Prefixed               37           18        48.6%
Browserhacks                   0            0         0.0%

Values                     Total       Unique     Unique %
Colors                       161           86        53.4%
Gradients                     48           15        31.3%
Font-sizes                    53           20        37.7%
Font-families                 42           16        38.1%
Line-heights                  38           16        42.1%
Text-shadows                   0            0         0.0%
Box-shadows                   16            6        37.5%
Z-indexes                     21           13        61.9%
Vendor Prefixed                2            2       100.0%
Browserhacks                   0            0         0.0%
Units                        591            8         1.4%
```

**Comment by dgrebb** [comment]
# SvelteKit Buildtime 23.11.02 18:10

## `dg f b s`

### After moving css imports into components

```shell
> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
✓ built in 14.28s
```

**Comment by dgrebb** [comment]
# PRD Wallace | 23.11.05 01:18

## After CSS Nesting Refactor

```shell
Testing CSS on PROD
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- -100  160k  100  160k    0     0   582k      0 --:--:-- --:--:-- --:--:--  588k
───────────────────────────────────────────────────────────
Lines of Code │ Filesize │ Rules │ Selectors │ Declarations
4,438         │ 164.5KB  │ 1,000 │ 2,022     │ 2,304
───────────────────────────────────────────────────────────

Comments                      0B    (0 items)
Embedded Content              0B    (0 items)

Rulesets             Most common      Average      Maximum
Selectors / rule               1         2.03           21
Declarations / rule            1         2.29           75
Empty rules                                              0

Selectors            Most common      Average      Maximum
Complexity                     3         5.63           21
Specificity                0/2/1  0.1/2.7/1.0        1/8/3

                           Total       Unique        Ratio
All Selectors              2,022        1,500        74.2%
ID Selectors                 118          104        88.1%
Accessibility                  1            1       100.0%
Vendor prefixed               63           56        88.9%

AtRules                    Total       Unique     Unique %
@media                        99           12        12.1%
@supports                      2            2       100.0%
@font-face                     6            6       100.0%
@import                        0            0         0.0%
@keyframes                     1            1       100.0%
@container                     0            0         0.0%
@property                      0            0         0.0%

Declarations               Total       Unique     Unique %
All Declarations           2,304          884        38.4%
!important                    53

Properties                 Total       Unique     Unique %
All Properties             2,304          298        12.9%
Custom Properties            247          149        60.3%
Vendor Prefixed               56           21        37.5%
Browserhacks                   0            0         0.0%

Values                     Total       Unique     Unique %
Colors                       359          114        31.8%
Gradients                     70           14        20.0%
Font-sizes                    51           20        39.2%
Font-families                 40           18        45.0%
Line-heights                  35           14        40.0%
Text-shadows                   4            1        25.0%
Box-shadows                   55            8        14.5%
Z-indexes                     25           13        52.0%
Vendor Prefixed                1            1       100.0%
Browserhacks                   0            0         0.0%
Units                        704            8         1.1%
```

**Comment by dgrebb** [comment]
# STG Wallace | 23.11.05 01:18

## After CSS Nesting Refactor

```shell
Testing CSS on STG
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- -  0     0    0     0    0     0      0      0 --:--:-- --:--:-- -100 53755  100 53755    0     0   332k      0 --:--:-- --:--:-- --:--:--  336k
───────────────────────────────────────────────────────────
Lines of Code │ Filesize │ Rules │ Selectors │ Declarations
1,272         │ 53.7KB   │ 229   │ 410       │ 839
───────────────────────────────────────────────────────────

Comments                    153B    (2 items)
Embedded Content              0B    (0 items)

Rulesets             Most common      Average      Maximum
Selectors / rule               1         1.79           21
Declarations / rule            1         3.59           44
Empty rules                                              0

Selectors            Most common      Average      Maximum
Complexity                     1         2.77            9
Specificity                0/1/1  0.0/1.2/0.8        1/2/1

                           Total       Unique        Ratio
All Selectors                410          279        68.0%
ID Selectors                   6            6       100.0%
Accessibility                  1            1       100.0%
Vendor prefixed               14           12        85.7%

AtRules                    Total       Unique     Unique %
@media                        17           12        70.6%
@supports                      0            0         0.0%
@font-face                     6            6       100.0%
@import                        0            0         0.0%
@keyframes                     0            0         0.0%
@container                     0            0         0.0%
@property                      0            0         0.0%

Declarations               Total       Unique     Unique %
All Declarations             839          499        59.5%
!important                     9

Properties                 Total       Unique     Unique %
All Properties               839          224        26.7%
Custom Properties            247          122        49.4%
Vendor Prefixed               15            8        53.3%
Browserhacks                   0            0         0.0%

Values                     Total       Unique     Unique %
Colors                       103           66        64.1%
Gradients                     22           13        59.1%
Font-sizes                    29           14        48.3%
Font-families                 23           14        60.9%
Line-heights                  29           14        48.3%
Text-shadows                   0            0         0.0%
Box-shadows                    4            3        75.0%
Z-indexes                      5            4        80.0%
Vendor Prefixed                2            2       100.0%
Browserhacks                   0            0         0.0%
Units                        343            7         2.0%
```

**Comment by dgrebb** [comment]
# Treeshaking Enhancement

## `svelte-meta-tags`

I changed the import to `import MetaTags from 'svelte-meta-tags/MetaTags.svelte';` and reduced the bundle size by almost 100KiB.

### Before

`/s/immutable/entry/app.01187fb1.js · 91.9 KiB (29%)`

![Image](https://github.com/dgrebb/dgrebb.com/assets/445891/bc75de20-28e5-4abc-94ed-a3d82e55c9aa)

### After

`/s/immutable/entry/app.9adc4d39.js · 7.8 KiB (3%)`

![Image](https://github.com/dgrebb/dgrebb.com/assets/445891/f9ea3e0b-efc9-4ea5-98fd-f8b6ecf082d8)
