### ISSUE TITLE
🧹 [CHORE]: FE - refactor all Tailwind helpers and layers

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#926]
### Summary

Utilities, base, layers, etc should be refactored as CSS vars etc.

### Tasks

- [ ] check for any breakpoint helpers and replace
- [ ] remove/refactor utilities.css
- [ ] add `screen` to all `@media` queries
- [ ] other refactoring as needed
- [ ] test
- [ ] visual regression
- [ ] snapshots of file/bundle sizes
