### ISSUE TITLE
🧹 [CHORE]: FE - update noscript.css

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#927]
### Summary

Review current state of `noscript` browsers and update `noscript.css` to account for `prefers-reduced-motion: reduce` and other hidden/shown states that break the user experience.

### Tasks

- [ ] run latest local build
- [ ] test browsers with JS off
- [ ] update `noscript.css`
- [ ] vis reg
- [ ] done
