### ISSUE TITLE
🧹 [CHORE]: FE - check HTML for any leftover tailwind classes

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#928]
### Summary

There may be some tailwind classes left behind in `.svelte` and `.html` files and components. Check SVG as well.

### Tasks

- [x] check for `class="` instances and review classnames
- [x] check for conditional use of classnames and instances of tailwind visibility helpers, etc being used
- [x] vis reg
- [x] update as needed
- [x] vis reg

**Comment by dgrebb** [comment]
Closed with #945
