### ISSUE TITLE
✨ [FEAT]: FE - Import CSS directly into components where possible

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#929]
### Summary

Take a before/after sampling of performance and refactor `svelte` components with CSS imports rather than one large CSS injection into `index.html`.

### Tasks

- [x] #692 
- [ ] take perf snapshot and payloads (css specific)
- [ ] inventory of current CSS files
- [ ] refactoring of CSS into view-specific use imports (such as posts, post, privacy, category)
- [ ] add imports to svelte
- [ ] vis reg
- [ ] update
- [ ] take after snapshot
- [ ] record findings

### URL

https://www.dgrebb.com/
