### ISSUE TITLE
🧹 [CHORE]: FE - refactor CSS themeing

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#930]
### Summary

Remove unused color variables, create names for element color properties, and move element-specific styles back into their [component].css files.

### Tasks

- [x] #691 
- [x] take before snapshots
- [x] create names for the various use cases
- [x] move component-specific rules in theme.css to their component css file
- [x] refactor `theme.css` with new color variable names, applying dark/light in their browser matcher rulesets
- [x] vis reg
- [x] fix and adjust
- [x] take after snapshots

**Comment by dgrebb** [comment]
closed with #939
