### ISSUE TITLE
🎬 [PLAN]: Final Perf metrics from CSS Refactor

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#931]
### Summary

Take final browser, report, filesize, buildtimes etc. post-refactor.

### Tasks

- [x] chrome perf
  - [x] home, privacy, post, posts, category
  - [x] navigating through the site
- [x] lighthouse reports
- [x] build size
- [x] local build time of stg
- [x] gh-stg build time

### URL

https://www.dgrebb.com/

**Comment by dgrebb** [comment]
# PROD Before

![Image](https://github.com/dgrebb/dgrebb.com/assets/445891/9e2db3af-b80f-4d7d-adff-63088baa20d4)

# PROD After

![image](https://github.com/dgrebb/dgrebb.com/assets/445891/5b2c0a63-de05-4eb0-a1fc-84eaf0a537d7)

**Comment by dgrebb** [comment]
# PROD Before

![Image](https://github.com/dgrebb/dgrebb.com/assets/445891/7e7ad485-640e-49f6-9779-d5717e0407ce)

# PROD After

![image](https://github.com/dgrebb/dgrebb.com/assets/445891/c415abba-55df-4e61-a274-1c1044463ae7)

**Comment by dgrebb** [comment]
# PROD Before

```shell
Testing CSS on PROD
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  160k  100  160k    0     0   443k      0 --:--:-- --:--:-- --:--:--  446k
───────────────────────────────────────────────────────────
Lines of Code │ Filesize │ Rules │ Selectors │ Declarations
4,438         │ 164.5KB  │ 1,000 │ 2,022     │ 2,304
───────────────────────────────────────────────────────────

Comments                      0B    (0 items)
Embedded Content              0B    (0 items)

Rulesets             Most common      Average      Maximum
Selectors / rule               1         2.03           21
Declarations / rule            1         2.29           75
Empty rules                                              0

Selectors            Most common      Average      Maximum
Complexity                     3         5.63           21
Specificity                0/2/1  0.1/2.7/1.0        1/8/3

                           Total       Unique        Ratio
All Selectors              2,022        1,500        74.2%
ID Selectors                 118          104        88.1%
Accessibility                  1            1       100.0%
Vendor prefixed               63           56        88.9%

AtRules                    Total       Unique     Unique %
@media                        99           12        12.1%
@supports                      2            2       100.0%
@font-face                     6            6       100.0%
@import                        0            0         0.0%
@keyframes                     1            1       100.0%
@container                     0            0         0.0%
@property                      0            0         0.0%

Declarations               Total       Unique     Unique %
All Declarations           2,304          884        38.4%
!important                    53

Properties                 Total       Unique     Unique %
All Properties             2,304          298        12.9%
Custom Properties            247          149        60.3%
Vendor Prefixed               56           21        37.5%
Browserhacks                   0            0         0.0%

Values                     Total       Unique     Unique %
Colors                       359          114        31.8%
Gradients                     70           14        20.0%
Font-sizes                    51           20        39.2%
Font-families                 40           18        45.0%
Line-heights                  35           14        40.0%
Text-shadows                   4            1        25.0%
Box-shadows                   55            8        14.5%
Z-indexes                     25           13        52.0%
Vendor Prefixed                1            1       100.0%
Browserhacks                   0            0         0.0%
Units                        704            8         1.1%
```

# STG After

```shell
Testing CSS on STG
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 54823  100 54823    0     0   152k      0 --:--:-- --:--:-- --:--:--  153k
───────────────────────────────────────────────────────────
Lines of Code │ Filesize │ Rules │ Selectors │ Declarations
1,275         │ 54.8KB   │ 230   │ 409       │ 843
───────────────────────────────────────────────────────────

Comments                    153B    (2 items)
Embedded Content              0B    (0 items)

Rulesets             Most common      Average      Maximum
Selectors / rule               1         1.78           21
Declarations / rule            1         3.60           44
Empty rules                                              0

Selectors            Most common      Average      Maximum
Complexity                     1         2.75           10
Specificity                0/1/1  0.0/1.2/0.8        1/2/1

                           Total       Unique        Ratio
All Selectors                409          278        68.0%
ID Selectors                   6            6       100.0%
Accessibility                  1            1       100.0%
Vendor prefixed               14           12        85.7%

AtRules                    Total       Unique     Unique %
@media                        17           12        70.6%
@supports                      0            0         0.0%
@font-face                     6            6       100.0%
@import                        0            0         0.0%
@keyframes                     0            0         0.0%
@container                     0            0         0.0%
@property                      0            0         0.0%

Declarations               Total       Unique     Unique %
All Declarations             843          499        59.2%
!important                     9

Properties                 Total       Unique     Unique %
All Properties               843          224        26.6%
Custom Properties            247          122        49.4%
Vendor Prefixed               15            8        53.3%
Browserhacks                   0            0         0.0%

Values                     Total       Unique     Unique %
Colors                       104           65        62.5%
Gradients                     22           13        59.1%
Font-sizes                    29           14        48.3%
Font-families                 23           14        60.9%
Line-heights                  29           14        48.3%
Text-shadows                   0            0         0.0%
Box-shadows                    4            3        75.0%
Z-indexes                      6            4        66.7%
Vendor Prefixed                2            2       100.0%
Browserhacks                   0            0         0.0%
Units                        343            7         2.0%
```

**Comment by dgrebb** [comment]
# Treeshaking

## `svelte-meta-tags`

I changed the import to `import MetaTags from 'svelte-meta-tags/MetaTags.svelte';` and reduced the bundle size by almost 100KiB.

### Before

`/s/immutable/entry/app.01187fb1.js · 91.9 KiB (29%)`

![Image](https://github.com/dgrebb/dgrebb.com/assets/445891/bc75de20-28e5-4abc-94ed-a3d82e55c9aa)

### After

`/s/immutable/entry/app.9adc4d39.js · 7.8 KiB (3%)`

![Image](https://github.com/dgrebb/dgrebb.com/assets/445891/f9ea3e0b-efc9-4ea5-98fd-f8b6ecf082d8)

**Comment by dgrebb** [comment]
## Final Local Build Times and Sizes

### `main` branch, unmerged with performance enhancements

```shell
> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
✓ built in 18.09s
```

`build - 7,309,638 bytes (7.9 MB on disk) for 311 items`

### `develop` branch with performance enhancements

```shell
> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
✓ built in 9.77s
```

`build - 4,476,780 bytes (5.2 MB on disk) for 338 items`
