### ISSUE TITLE
🧹 [CHORE]: Upgrade to and patch Strapi@4.15.2

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#957]
### Summary

https://github.com/strapi/strapi/releases/tag/v4.15.2

### Tasks

- [ ] update strapi
- [ ] apply/recreate patches
- [ ] test dynamic component add/remove functionality
- [ ] deploy to STG
- [ ] test
- [ ] PR/merge

**Comment by dgrebb** [comment]
4.15.2 is broken. closing.
