### ISSUE TITLE
🧹 [CHORE]: CMS - test update/patch to strapi@4.15.4

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#969]
### Summary

https://github.com/strapi/strapi/releases/tag/v4.15.4

### Tasks

- [ ] get last 4.15 patch files in place
- [ ] determine if patching is possible
- [ ] run update
- [ ] test dynamic component
