### ISSUE TITLE
✨ [FEAT]: CI - Release Workflow w/ commitizen-tools and git-cliff

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#970]
### Summary

Create a workflow to move release management into GitHub. Changelog notes for GitHub release tags will continue to be manual, but the commits, deployments, and PRs should be handled by GitHub actions.

### Tasks

- [ ] update `act` and get things set up locally
- [ ] fork https://github.com/commitizen-tools/commitizen-action
- [ ] add git-cliff to the dockerfile via https://github.com/orhun/git-cliff-action/blob/main/entrypoint.sh
- [ ] test
- [ ] test github
- [ ] iterations
- [ ] test
- [ ] done

### URL

https://www.dgrebb.com/

**Comment by dgrebb** [comment]
this is already done
