### ISSUE TITLE
✨ [FEAT]: CMS - add CV Singletons

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#971]
### Summary

Create the entity for CV landing page content.

### Tasks

- [x] create CV landing and fields
- [x] create Positions landing and fields
- [x] create Skills landing and fields
- [x] create Projects landing and fields
- [x] create Awards landing and fields
- [x] create Organizations landing and fields
- [x] create Industries landing and fields

### URL

https://www.dgrebb.com/
