### ISSUE TITLE
✨ [FEAT]: FE - Display Lo-FI Positions and Timeline on CV Landing Page

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#976]
### Summary

Display positions in order of end date in timeline component on CV landing page. 

### Tasks

- [ ] add positions API
- [ ] add positions to CV page
- [ ] add timeline via #827

### URL

https://www.dgrebb.com/
