### ISSUE TITLE
🐞 [BUG]: FE - CSP Throwing Errors for .vtt video caption files

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dgrebb.com#999]
### What happened?

Check it out and fix it! Probably a change in S3 configuration or using CMS as the caption provider.

### Tasks

- [ ] research solutions to s3/vtt/firefox/mime/csp 
- [ ] fix? if not
- [ ] use CMS field to drive subtitles
